### ISSUE TITLE
patch-herb

### ISSUE THREAD

**Issue by Meridaw** [RetroCro/TurtleWoW-Mods#2]
https://github.com/seacrabsam/patch-herb

Turns (most) herbs pink for easy finding.

**Comment by RetroCro** [comment]
Thanks added 
https://github.com/RetroCro/TurtleWoW-Mods?tab=readme-ov-file#119-pink-herbs

**Comment by RetroCro** [comment]
https://github.com/RetroCro/TurtleWoW-Mods?tab=readme-ov-file#119-pink-herbs

**Comment by RetroCro** [comment]
https://github.com/RetroCro/TurtleWoW-Mods?tab=readme-ov-file#119-pink-herbs
